version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-apache-laravel
    container_name: authorization_php
    restart: always
    ports:
      - "8065:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_authorization_db
  mysql_authorization_db:
    image: mysql:latest
    restart: always
    container_name: mysql_authorization
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authorization_db
    ports:
      - "3365:3306"
    volumes:
      - ./init_authorization.sql:/docker-entrypoint-initdb.d/init_authorization.sql
      - mysql_authorization_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8066:80"
    environment:
      PMA_HOST: mysql_authorization_db
      PMA_ARBITRARY: 1
volumes:
  mysql_authorization_data:
    driver: local